from solver.gradient_descent import *
from solver.newton import *
from solver.linearreg import *
from solver.ridge import *
from solver.polyreg import *
from solver.lasso import *
from solver.logisticreg import *
from solver.svm import *
from solver.kmeans import *
from solver.pca import *
